name: PHP Linting

on: pull_request

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@latest
          with:
            preset: laravel
            parallel: true
            useComposer: true
            verboseMode: true
            testMode: true
            onlyDirty: false
